version: '3.6'

services: 
  jupyterlab:
    build: .
    ipc: host
    ports: 
      - 8888:8888
    volumes: 
      - ./app:/app
      - ./data:/app/data
    deploy:
      resources: 
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]

